# Generated by Django 4.0.3 on 2022-05-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_2', models.FloatField()),
                ('mass_zeta_potential', models.FloatField()),
                ('mass_concentration', models.FloatField()),
                ('mass_ev', models.FloatField()),
                ('concentration_2', models.FloatField()),
                ('zeta_potential_2', models.FloatField()),
                ('zeta_potential_concentration', models.FloatField()),
                ('concentration_toxicity', models.FloatField()),
                ('zeta_potential_toxicity', models.FloatField()),
                ('mass', models.FloatField()),
                ('energy_source', models.FloatField()),
                ('shape_Janus', models.FloatField()),
                ('concentration_ev', models.FloatField()),
                ('toxicity', models.FloatField()),
                ('bioapplicable', models.FloatField()),
            ],
        ),
    ]
